detection:
    checkpoint_file: ./misc/checkpoints/swin_transformer/ctmc.pth
    config_file: ./misc/checkpoints/swin_transformer/ctmc.py
    full_window: yes

tracking:
    analyse: no
    dets_min_score: 0.25
    epic_tracker:
        feats:
            temp_dist:
                thresh: [-1, 5]
            iou:
                thresh: [0.5, 0.5]
                weight: [1, 1]
            euclid_dist:
                enabled: [no, no]
            boundary:
                enabled: [no, no]
        glob_temp_dist: [1, 5]
